name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Executa o workflow apenas para tags que começam com "v"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile app.py

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          asset_path: dist/app
          asset_name: app.exe
          asset_content_type: application/x-msdownload
